// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb9uaaAw3Yg7WLU2vlGVxHOj2S2ssUg8A',
    appId: '1:511736524993:web:d6b58cf60dd2b5a264e440',
    messagingSenderId: '511736524993',
    projectId: 'priva-socialmedia',
    authDomain: 'priva-socialmedia.firebaseapp.com',
    storageBucket: 'priva-socialmedia.appspot.com',
    measurementId: 'G-WCTFV6361V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzaUSOC7TLG4VgMRS6X_AwDkrLs6iRE60',
    appId: '1:511736524993:android:1b5ee9d5fcba00d664e440',
    messagingSenderId: '511736524993',
    projectId: 'priva-socialmedia',
    storageBucket: 'priva-socialmedia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKOEN1FJ6K9crM5D0cJDJ5pxlEUUMh2Ho',
    appId: '1:511736524993:ios:77d100096651f9c564e440',
    messagingSenderId: '511736524993',
    projectId: 'priva-socialmedia',
    storageBucket: 'priva-socialmedia.appspot.com',
    iosBundleId: 'com.example.privaSocialmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKOEN1FJ6K9crM5D0cJDJ5pxlEUUMh2Ho',
    appId: '1:511736524993:ios:9c46dd829432a67a64e440',
    messagingSenderId: '511736524993',
    projectId: 'priva-socialmedia',
    storageBucket: 'priva-socialmedia.appspot.com',
    iosBundleId: 'com.example.privaSocialmedia.RunnerTests',
  );
}
